version: '2'
services:

  postgres:
    image: "postgres:alpine"
    container_name: ark-testnet-postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: ark_testnet
     POSTGRES_USER: ark

  core:
    build: .
    image: core
    container_name: ark-testnet-core
    ports:
     - "4000:4000"
     - "4003:4003"
     - "4040:4040"
    volumes:
     - d:/core:/core
    tty: true
    privileged: true
    links:
     - postgres
    depends_on:
      - postgres
    command:
      - /bin/sh
      - -c
      - |
          /entrypoint.sh
volumes:
  postgres:
  core:
